spring:
  datasource:
    url: ${rdbm.server_url}/netobjex
    driver-class-name: org.postgresql.Driver
    username: netobjex
    password: 911NetObjexIoT
    maximum-pool-size: 30
    
messagebroker:
    broker:
      username: admin
      password: admin
      host: 54.86.239.111
    stomp:
      port: 61613
      ## Wildcard for STOMP is *
      domainSeparator: .
    mqtt:
      port: 1883
      ## Wildcard for MQTT is #
      domainSeparator: /
      
netobjex:
  apiGateway:
    baseEndpoint:  http://api-dev.netobjex.com/netobjexapi/gateway/rest/com/tw/netobjex/PublicAPI/
    
survey:
  short:
    baseurl:  http://dev.nbj.co/
